services:

  akile_monitor_server:
    image: niliaerith/akile_monitor_server
    container_name: akile_monitor_server
    hostname: akile_monitor_server
    restart: always
    ports:
      - 3000:3000 #主控服务端 端口
    volumes:
      - /CHANGE_PATH/akile_monitor/server/config.json:/app/config.json 
      - /CHANGE_PATH/akile_monitor/server/ak_monitor.db:/app/ak_monitor.db
      - /CHANGE_PATH/akile_monitor/caddy/config.json:/usr/share/caddy/config.json
    environment:
      TZ: "Asia/Shanghai"

  akile_monitor_fe:
    image: niliaerith/akile_monitor_fe
    container_name: akile_monitor_fe
    hostname: akile_monitor_fe
    restart: always
    ports:
      - 80:80 #前端 端口
    volumes:
      - /CHANGE_PATH/akile_monitor/caddy/config.json:/usr/share/caddy/config.json # 与环境变量二选一
    environment:
      TZ: "Asia/Shanghai"
      SOCKETURL: "ws://192.168.31.64:3000/ws" # 与配置文件二选一
      APIURL: "http://192.168.31.64:3000" # 与配置文件二选一

  akile_monitor_client:
    image: niliaerith/akile_monitor_client
    container_name: akile_monitor_client
    hostname: akile_monitor_client
    restart: always
    network_mode: host
    volumes:
      - /CHANGE_PATH/akile_monitor/client/client.json:/app/client.json
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: "Asia/Shanghai"